platform: linux

image_resource:
  type: docker-image
  source:
    repository: busybox
    tag: latest

inputs:
  - name: concourse-prs
  - name: community-metrics

run:
  path: community-metrics/tasks/collect-prs.sh
